server:
  port: 8000

spring:
  application:
    name: zuul-gateway

zuul:
  routes:
    order-server:
      path: /order/**


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:5060/eureka




